POST http://localhost:5000/create-checkout-session HTTP/1.1
Content-Type: application/json

{
   "line_items":[
      {
         "quantity":1,
         "price_data":{
            "currency":"USD",
            "unit_amount": 200,
            "product_data":{
               "name":"Studio Bag"
            }
         }
      }
   ],
   "customer_email":"joyawilliams@gmail.com"
}

###